MusicTesting/Models/DataModel/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicTesting.Models.DataModel
{
    public class Message
    {
        public int MessageId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public string FileDir { get; set; }
        public DateTime Date{ get; set; }
        public bool IsRead { get; set; }
        public string AuthorName { get; set; }
    }
}

MusicTesting/Models/Messages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public int FromUser { get; set; }
        public int ToUser { get; set; }
        public string Header { get; set; }
        public string Body { get; set; }
        public string FileDir { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsRead { get; set; }
    }
}

MusicTesting/Models/ViewModel/MessagesView.cs
using MusicTesting.Models.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicTesting.Models.ViewModel
{
    public class MessagesView:BaseView
    {
        public List<Message> MessageList { get; set; }
        public MessagesView() {
            MessageList = new List<Message>();
        }

        public MessagesView(int userId)
        {
            MessageList = new List<Message>();
            using (var DB  = new MTDBEntities())
            {
                var result = DB.Database.SqlQuery<Message>(@"
                    select
m.Id as MessageId,
m.FromUser as FromUserId,
m.ToUser as ToUserId,
m.Header, m.Body, m.[Date], m.IsRead,
p.FirstName + ' ' + p.LastName as AuthorName
from Messages as m
left join Person as p on m.FromUser = p.UserId
where m.ToUser = @p0 or m.FromUser = @p0
order by [Date] desc
                    ", userId);
                if (result!= null)
                    {
                        MessageList = result.ToList<Message>();
                    }
            }
        }
        public void SendMessage(int fromUserId, int toUserId, string hader = "", string body = "", string fileDire = "")
        {
            var mes = new Messages()
            {
                Body = body,
                Header = hader,
                IsRead = false,
                Date = DateTime.Now,
                FromUser = fromUserId,
                ToUser = toUserId,
                FileDir = fileDire
            };
            using (var DB = new MTDBEntities())
            {
                DB.Entry(mes).State = System.Data.Entity.EntityState.Added;
                DB.SaveChanges();
            }
        }

        public void ReadMessage(int messageId)
        {
            using (var DB = new MTDBEntities())
            {
                DB.Database.
                    ExecuteSqlCommand(@"update Messages set IsRead = 1 where Id = @p0", messageId);
            }
        }
    }
}

MusicTesting/Controllers/ComunicationController.cs
using MusicTesting.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MusicTesting.Controllers
{
    public class ComunicationController : Controller
    {
        public ActionResult GetMessages(int userId)
        {
            var model = new MessagesView(userId);
            if (Session["User"] != null)
            {
                model.CurrentUser = (User)Session["User"];
            }        
            Session["User"] = model.CurrentUser;
            return View("Messages", model);
        }

        public ActionResult SendReplyMessage(int fromUserId, int toUserId, string header, string body, string fileDire)
        {
           new MessagesView().SendMessage(fromUserId, toUserId, header, body, fileDire);
            var model = new MessagesView(fromUserId);
            if (Session["User"] != null)
            {
                model.CurrentUser = (User)Session["User"];
            }
            Session["User"] = model.CurrentUser;
            return View("Messages", model);
           // return Json(null, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public ActionResult SendMessage(int fromUserId, int toUserId, string header, string body)
        {
            new MessagesView().SendMessage(fromUserId, toUserId, header, body, null);
            return Json(null, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public ActionResult ReadMessage(int messagId)
        {
            new MessagesView().ReadMessage(messagId);
            return Json(null, JsonRequestBehavior.DenyGet);
        }
    }
}

MusicTesting/Views/Comunication/Messages.cshtml
@{
    ViewBag.Title = "Messages";
}
@using MusicTesting.Models.ViewModel;
@model MessagesView
<script>
    function readMessage(messageId, fromId, toId, header, body, authorName) {
        var toUserId = document.getElementById('modalMessagetoUserId')
        if (toUserId != null) {
            toUserId.value = fromId;
        }

        var head = document.getElementById('modalMessageHeader')
        if (head != null) {
            head.value = header
        }

        var mBody = document.getElementById('modalMessageBody')
        if (mBody != null) {
            mBody.value = body;
        }

        var read = document.getElementById('readMessageIcon ' + messageId);
        if (read != null && (fromId != @Model.CurrentUser.UserId)) {
            read.src = document.getElementById('hiddenSrcReadMessage').src;
        }

        var window = document.getElementById('openModalReadWindow');
        if (window != null) {
            window.click();
        }

        if (fromId != @Model.CurrentUser.UserId)
        {
            var reply = document.getElementById('modalMessaegReply');
            if(reply!= null)
            {
                reply.style.visibility = 'visible';
            }
            var message = document.getElementById('messageModalForm');
            if (message) {
                message.click();
                $.ajax({
                    url: '@Url.Action("ReadMessage", "Comunication")',
                    type: 'post',
                    cache: false,
                    async: true,
                    data: { messagId: messageId },
                    success: function (result) {
                    }
                });
            }
        }
    }

    function prepareMessageWindow()
    {
        var submit = document.getElementById('modalMessageSumbit')
        if (submit != null)
        {
            submit.style.visibility = 'visible';
         }
        var reply = document.getElementById('modalMessaegReply')
        if(reply!= null)
        {
            reply.style.visibility = 'hidden';
        }

        var head = document.getElementById('modalMessageHeader')
        if (head != null) {
            head.disabled = false;
            head.value = '';
        }
        var mBody = document.getElementById('modalMessageBody')
        if (mBody != null) {
            mBody.disabled = false;
            mBody.value = '';
        }
    }

    function formSubmit() {

        if (@Model.CurrentUser.UserId != document.getElementById('modalMessagetoUserId').value) {
            $.ajax({
                url: '@Url.Action("SendReplyMessage", "Comunication")',
                data: $('#messageModalForm').serialize(),
                success: function (result) {
                    prepareMessageWindow();
                    var close = document.getElementById('modalMessageClose');
                    if (close)
                        close.click();
                    window.location.reload();
                }
            });
        }
        else alert('Ви не можете надсилати собі повіомлення');
    }
</script>

    <section style="background:linear-gradient(to right, #25c481, #25b7c4);">
        <!--for demo wrap-->
        <div class="tbl-header">
            <table cellpadding="0" cellspacing="0" border="0">
                <thead>
                    <tr>
                        <th>In/Out</th>
                        <th>Author</th>
                        <th>Header</th>
                        <th>Date</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="tbl-content">
            <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    @if (@Model.MessageList != null)
                    {
                        foreach (var item in @Model.MessageList)
                        {
                            <tr href="#openModal"; onclick="readMessage(@item.MessageId, 
                                 @item.FromUserId,
                                 @item.ToUserId,
                                '@item.Header.Replace(System.Environment.NewLine, " ")',
                                '@item.Body.Replace(System.Environment.NewLine, " ")',
                                '@item.AuthorName')">
                               <td>
                                    @if (@item.IsRead)
                                    {
                                        <img src="~/Content/images/read-message.png" id="readMessageIcon @item.MessageId" class="info-arrow">
                                    }
                                    else
                                    {
                                        <img src="~/Content/images/new-in-message.png"  id="readMessageIcon @item.MessageId" class="info-arrow">
                                    }

                                @if (@item.FromUserId == @Model.CurrentUser.UserId)
                                {
                                   <img src="~/Content/images/message-out.png" class="info-arrow">
                                }
                                else
                                {
                                    <img src="~/Content/images/message-in.png" class="info-arrow">
                                }
                                </td>
                                <td>
                                    @item.AuthorName
                                </td>
                                <td>@item.Header</td>
                                <td>@item.Date</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </section>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="~/Content/js/message-index.js"></script>

<img id="hiddenSrcReadMessage" src="~/Content/images/read-message.png" style="display:none;">
<div id="openModal" class="modalDialog">
    <div>
        <a href="#close" title="Close"  id="modalMessageClose" class="close">X</a>
        <form id="messageModalForm">
            <ul class="form-style-1">
                <li>
                    <input type="hidden" value="@Model.CurrentUser.UserId" name="fromUserId" id="modalMessagefromUserId">
                    <input type="hidden" value="@Model.CurrentUser.UserId" name="toUserId" id="modalMessagetoUserId">
                    <input type="hidden" value="" name="fileDire" id="modalMessagefileDire">
                    <label>Заголовок:</label>
                    <input type="text" name="header" class="field-long"  disabled id="modalMessageHeader"/>
                </li>
                <li>
                    <label>Ваше повідомлення <span class="required">*</span></label>
                    <textarea name="body" id="modalMessageBody" class="field-long field-textarea" disabled ></textarea>
                </li>
                <li>
                    <input onclick="formSubmit()" type="button" id="modalMessageSumbit" value="Надіслати"  style="visibility:hidden"/>
                    <input type="button" value="Відповісти" id="modalMessaegReply" onclick="prepareMessageWindow()" style="visibility:hidden; float:right;" />
                </li>
            </ul>
        </form>
    </div>
</div>
<a href="#openModal" id="openModalReadWindow" style="display:none"></a>